### ISSUE TITLE
Parallelize ANTs

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#31]
- First we need to understand how to parallelize ANTs across multiple machines
- There are two job options:
  - Ordered
  - Self organizing
- After we have parallelized ANTs, we need to figure out how to fit it into one of these two models.

**Comment by Chris210634** [comment]
We need to make the ANTs plug-in fault tolerant. When one worker fails, a new worker should be able to pick up where the failed worker left off. (Currently new worker will fail immediately and remaining workers will time out waiting for failed worker)

**Comment by Chris210634** [comment]
Eventually, we want a mechanism to automatically set the number of threads per pod based on resource limits set.
