### ISSUE TITLE
Stand up a new public ChRIS Backend/pfcon for the contest

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#38]

**Comment by danmcp** [comment]
Will need to point to pman and pfioh running on the MOC.

**Comment by rudolphpienaar** [comment]
A dockerized pfcon is available here:

     fnndsc.childrens.harvard.edu:5005

It is running pfcon ver 1.5.6.4 which has the massive list of internal hardcoded targets.

**Comment by mairin** [comment]
(clarification from today's status meeting, the above pfcon does include MOC integration)
