### ISSUE TITLE
Define way to get description and example images into ChRIS UI for each plugin

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#39]
The plugin help text might be enough for both.  But we at least need an official answer for plugin writers as to how they let people know what their plugin should be used for.

**Comment by danmcp** [comment]
@rudolphpienaar @jbernal0019 FYI

**Comment by jbernal0019** [comment]
Hey @danmcp I’m not sure about exactly what you mean with this issue but I’ll try to explain here the plugin app description mechanism currently implemented.

There are two types of app descriptions associated with a CUBE plugin app, one is given by the **--help** flag typically found in CLI applications and that usually prints a CLI app usage:

`~$ docker run --rm fnndsc/pl-simplefsapp simplefsapp.py --help`

Researchers are very use to this flag.

The second is how the plugin app provides a description of itself (parameters and their corresponding types) not to humans but to any service that wants to produce a UI for the plugin app. For this purpose the plugin app can automatically generate a JSON representation that is printed when the plugin is run with no arguments:

`~$ docker run --rm fnndsc/pl-simplefsapp`  

The CUBE’s REST API uses this JSON representation to generate appropriate responses to any HTTP requests targeting plugin information.

The nice thing of the current design is that the plugin app developer (usually a researcher with little knowledge about XML, JSON, REST APIs) doesn’t need to bother about how to generate any of those plugin app descriptions as they are automatically generated for him by just inheriting from the plugin app base class **ChrisApp**. That way he/she can focus on it’s research-related code. 

Here is an example of all the info that the plugin app developer needs to provide in the  app's code so the system can generate these two app descriptions:

`self.add_argument('--dir', dest='dir', type=ChrisApp.path, default='./',
 optional=True, help='look up directory')`

**Comment by danmcp** [comment]
@jbernal0019 This issue is addressed from the perspective of someone using the ChRIS UI.  How does a plugin writer explain to a user in the UI what the purpose of the plugin is and what an example of valid input might be?  The question was raised in the meeting this morning and I didn't know the answer.  It sounded like we didn't have an answer for examples.  And I had an open question of whether the text from --help also showed up in the ChRIS UI and whether that text is appropriate to use in the UI.

**Comment by jbernal0019** [comment]
OK @danmcp We can include the **_DESCRIPTION_** and **_CATEGORY_** class variables defined in the plugin app code as part of the JSON representation of the plugin. The FE will then get them through CUBE's REST API. They could be use to organize plugins in the FE's UI in a similar way to descriptions and categories in the Google app's store for instance.

**Comment by danmcp** [comment]
@jbernal0019 That sounds great!  The only other question I would have is how does a plugin writer know the valid categories?

**Comment by rudolphpienaar** [comment]
This is a WIP discussion! So we really have no idea at the moment. :-)

We could think of following an "app-store model" (like google play or apple store) where a plugin author who wants to submit to CHRIS would need to consult the CHRIS "store" (for lack of better word) for submission guidelines, which includes some category classification.

**Comment by jbernal0019** [comment]
@danmcp I also think that the ultimate goal of a system like CHRIS is to provide a way to define, store and execute pipelines of plugin apps. Pipelines are ordered collections of plugin apps. I think pipelines may be comprised of plugins from different categories. And there could be pipeline categories as well. Bu this is way to the future :)

**Comment by jbernal0019** [comment]
OK CUBE's REST API now returns several new plugin descriptors when a GET request is made to the plugin _list_, _detail_ and _search_ API end points. The plugin developer just need to fill out the corresponding class variables with their values in the plugin app code.
