### ISSUE TITLE
Pick 1 init container to download content with

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#45]
With the current swift integration, all job pods attempt to download the incoming images.  This logic needs to be changed to work with a scaled job.  In that case, we need to pick one worker (by the first in alphabetical order if we don't have a better option) to perform the initial download and have the other workers' init containers to wait for the init container performing the download to finish before they exit.

**Comment by umohnani8** [comment]
Fixed in https://github.com/FNNDSC/pman/pull/68
