### ISSUE TITLE
Avoid reading files into memory

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#49]
For pfioh/pman, we need to ensure files are never read fully into memory and are streamed from source to target.

**Comment by danmcp** [comment]
Potential Examples:

https://github.com/FNNDSC/pman/blob/master/openshift/pman-swift-publisher/put_data.py#L43

https://github.com/FNNDSC/pman/blob/master/openshift/pman-swift-publisher/get_data.py#L28

https://github.com/FNNDSC/pfioh/blob/master/pfioh/pfioh.py#L1249

https://github.com/FNNDSC/pfioh/blob/master/pfioh/swift_store.py#L117

https://github.com/FNNDSC/pfioh/blob/master/pfioh/mount_dir.py#L138

**Comment by husky-parul** [comment]
@betaredex Can we close this issue?

**Comment by betaredex** [comment]
Yes.
