### ISSUE TITLE
Performance/scale testing

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#6]
Will need to include:

- Throughput of pfioh
- Throughput of pman
- Performance of supported image plugins

Note: There is a worry about the performance of pman if the listeners fill up or under concurrency at all.

**Comment by husky-parul** [comment]
@danmcp 
co assign this issue to me

**Comment by husky-parul** [comment]
Source repo https://github.com/FNNDSC/ChRIS-E2E
