### ISSUE TITLE
Handle changes to plugins that are part of pipelines

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#61]
Situations that may occur:

- A plugin might be removed
- A plugin might have args added/removed

**Comment by jbernal0019** [comment]
The only thing that is allowed to change in a plugin while keeping the same version in the ChRIS store is the plugin's public repo which is not relevant to CUBE. Therefore effectively a plugin within a ChRIS pipeline never changes. A new version of an existing plugin in the ChRIS store can be registered to CUBE and ChRIS users can then create new pipelines that use the newer version.
