### ISSUE TITLE
Build out simple scaled plugin example

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#63]
Using the work done on ANTs parallelization (https://github.com/FNNDSC/pl-antsreg/), we want to build a simpler example to provide a basic example for plugin scale.

This might be a good example to implement:

https://opensource.com/article/17/12/image-manipulation-image-magick-perl

**Comment by husky-parul** [comment]
@betaredex create a PR in https://github.com/FNNDSC/pl-parallelex and close this issue
