### ISSUE TITLE
Research image processors to find the best fit

### ISSUE THREAD

**Issue by danmcp** [redhat-university-partnerships/radiology#7]

**Comment by danmcp** [comment]
Two potential image plugins to optimize:

http://elastix.isi.uu.nl/index.php
https://github.com/stnava/ANTs

**Comment by JacobTanenbaum** [comment]
http://trackvis.org/dtk/
https://surfer.nmr.mgh.harvard.edu/

**Comment by danmcp** [comment]
https://github.com/freesurfer/freesurfer

**Comment by danmcp** [comment]
https://www.cbica.upenn.edu/sbia/software/dramms/tutorials.html

**Comment by danmcp** [comment]
Software download: https://www.nitrc.org/projects/dramms/
demos for (medical) applications: https://www.cbica.upenn.edu/sbia/software/dramms/tutorials.html
manual: https://www.cbica.upenn.edu/sbia/software/dramms/_downloads/DRAMMS_Software_Manual.pdf
paper: http://www.nmr.mgh.harvard.edu/~you2/publications/Ou11.pdf

That's the registration part, which is the bottleneck. The skull stripping (or brain extraction for measuring brain volume) is built on top of registration. The main script can be found here https://www.nitrc.org/plugins/scmsvn/viewcvs.php/trunk/bin/picasso.sh?root=picasso&view=log
